version: 2
jobs:
   build:
     docker:
       - image: circleci/php:5.6
     steps:
       - checkout
      - echo "siguen los tests!!!"
test:
  override:
    - phpunit --bootstrap Email.php Emailtest.php 
 
