version: 2
jobs:
   build:
     docker:
       - image: circleci/php:5.6
     steps:
       - checkout
       - run: echo "hello world"
test:
  override:
    - mkdir -p $CIRCLE_TEST_REPORTS/phpunit
    - phpunit --log-junit $CIRCLE_TEST_REPORTS/phpunit/junit.xml --bootstrap xxEmail.php xxEmailtest.php
    
