version: 2
jobs:
   build:
     docker:
       - image: circleci/php:5.6
     steps:
       - checkout
       - run: echo "hello world"
test:
  override:
    - mkdir -p $CIRCLE_TEST_REPORTS/phpunit
    - phxpunitx --log-junit $CIRCLE_TESTx_REPORTS/phpunit/junit.xml --bootstrap Email.php Emailtest.php
    
