version: 2
jobs:
   build:
     docker:
       - image: circleci/php:5.6
     steps:
       - checkout
test:
  override:
    - mkdir -p $CIRCLE_TEST_REPORTS/phpunit
    - phxpunit --testdox-html $CIRCLE_TESTx_REPORTS/phpunit/index.html --bootstrap tests 
    - Email.php Emailtest.php
    - echo "hola"+5
    
