version: 2
jobs:
   build:
     docker:
       - image: circleci/php:5.6
     steps:
       - checkout
  artifacts:
      - "test.txt"
test:
  override:
    - mkdir -p $CIRCLE_TEST_REPORTS/phpunit
    - phpunit --testdox-html $CIRCLE_TEST_REPORTS/phpunit/index.html --bootstrap Email.php Emailtest.php
    - tests 
    - 
    - echo "hola"+5
    
