version: 2
jobs:
   build:
     docker:
       - image: circleci/php:5.6
     steps:
       - checkout
test:
  override:
    - mkdir -p $CIRCLE_ARTIFACTS/phpunit
    - phpunit --bootstrap Email.php Emailtest.php --testdox-html $CIRCLE_ARTIFACTS/phpunit/index.html 
    - echo "hola"
