version: 2
jobs:
   build:
     docker:
       - image: circleci/php:5.6
     steps:
       - checkout
      - echo "siguen los tests!!!"
test:
  override:
    - mkdir -p $CIRCLE_TEST_REPORTS/test-reports/
    - phpunit --testdox-html $CIRCLE_TEST_REPORTS/test-reports/index.html --bootstrap Email.php Emailtest.php 
 
