version: 2
jobs:
   build:
     docker:
       - image: circleci/<language>:<version TAG>
     steps:
       - checkout
       - run: echo "hello world"
test:
  override:
    - phpunit --bootstrap Email.php Emailtest.php
